language: python
dist: xenial
python:
  - "3.8"

before_install:
  - sh <(curl -L https://nixos.org/nix/install)
  - pip install poetry

install:
  - poetry install

# before_script:
#  -

script:
  - nix-shell
  - make setup
  - make release
  - poetry run python3 -m pytest --cov=radcad tests

after_success:
  - poetry run coveralls
