language: python
dist: xenial
python:
  - "3.8"

before_install:
  - pip install poetry

install:
  - poetry install

# before_script:
#  - poetry shell

script:
  - poetry run python3 -m pytest tests

