language: python
dist: xenial
python:
  - "3.8"

before_install:
  - sh <(curl -L https://nixos.org/nix/install)
  - . /home/travis/.nix-profile/etc/profile.d/nix.sh
  - pip install poetry

install:
  - poetry install

# before_script:
#  -

script:
  - pushd core
  - nix-shell --command "make setup && make release"
  - popd core
  - poetry run python3 -m pytest --cov=radcad tests

after_success:
  - poetry run coveralls
