language: python
dist: xenial
python:
  - "3.8"

before_install:
  # Fix for https://github.com/python-poetry/poetry/issues/3650
  # - pip install poetry
  - pip install poetry-core==1.0.0 poetry==1.1.4

install:
  - poetry install -E compat

# before_script:
#  -

script:
  - poetry run python3 -m pytest tests # --cov=radcad

# after_success:
  # - poetry run coveralls
