language: python
dist: xenial
python:
  - "3.8"

before_install:
  - sh <(curl -L https://nixos.org/nix/install)
  - . /home/travis/.nix-profile/etc/profile.d/nix.sh
  - pip install poetry
  - pushd core
  - nix-shell --command "make setup && make release-linux"
  - popd

install:
  - poetry install -E compat

# before_script:
#  -

script:
  - poetry run python3 -m pytest tests # --cov=radcad

# after_success:
  # - poetry run coveralls
