language: python
dist: xenial
python:
  - "3.8"

before_install:
  - pip install poetry

install:
  - poetry install -E compat

# before_script:
#  -

script:
  - poetry run python3 -m pytest tests # --cov=radcad

# after_success:
  # - poetry run coveralls
